app:
  env: dev
  timezone: Asia/Ho_Chi_Minh
  name: PHP Tool
  debug: true
database:
  driver: pdo_mysql
  host: localhost
  port: 3306
  user: root
  password: 
  charset: utf8mb4
  dbname: laravel
  